In [1]:
import pandas as pd

In [2]:
communes = pd.read_csv("data/raw/communes-france-2024.csv", low_memory=False)

In [3]:
communes.head()

,Unnamed: 0,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,...,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,gentile,url_wikipedia,url_villedereve
0,0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,...,206.0,272.0,46.153,4.926,46.153,4.926,Rural à habitat dispersé,NaN,https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01001-l-abergemen...
1,1,01002,L'Abergement-de-Varey,Abergement-de-Varey,à Abergement-de-Varey,de l'Abergement-de-Varey,l-abergement-de-varey,L'ABERGEMENT-DE-VAREY,COM,commune,...,290.0,748.0,46.009,5.428,46.009,5.428,Rural à habitat dispersé,"Abergementais, Abergementaises",https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01002-l-abergemen...
2,2,01004,Ambérieu-en-Bugey,Ambérieu-en-Bugey,à Ambérieu-en-Bugey,d'Ambérieu-en-Bugey,amberieu-en-bugey,AMBÉRIEU-EN-BUGEY,COM,commune,...,237.0,753.0,45.961,5.373,45.961,5.373,Centres urbains intermédiaires,"Ambarrois, Ambarroises",https://fr.wikipedia.org/wiki/fr:Ambérieu-en-B...,https://villedereve.fr/ville/01004-amberieu-en...
3,3,01005,Ambérieux-en-Dombes,Ambérieux-en-Dombes,à Ambérieux-en-Dombes,d'Ambérieux-en-Dombes,amberieux-en-dombes,AMBÉRIEUX-EN-DOMBES,COM,commune,...,265.0,302.0,45.996,4.912,45.996,4.912,Bourgs ruraux,Ambarrois,https://fr.wikipedia.org/wiki/fr:Ambérieux-en-...,https://villedereve.fr/ville/01005-amberieux-e...
4,4,01006,Ambléon,Ambléon,à Ambléon,d'Ambléon,ambleon,AMBLÉON,COM,commune,...,330.0,940.0,45.750,5.594,45.750,5.594,Rural à habitat dispersé,Ambléonais,https://fr.wikipedia.org/wiki/fr:Ambléon,https://villedereve.fr/ville/01006-ambleon

In [37]:
communes.columns

Index(['Unnamed: 0', 'code_insee', 'nom_standard', 'nom_sans_pronom', 'nom_a',
       'nom_de', 'nom_sans_accent', 'nom_standard_majuscule', 'typecom',
       'typecom_texte', 'reg_code', 'reg_nom', 'dep_code', 'dep_nom',
       'canton_code', 'canton_nom', 'epci_code', 'epci_nom', 'academie_code',
       'academie_nom', 'code_postal', 'codes_postaux', 'zone_emploi',
       'code_insee_centre_zone_emploi', 'population', 'superficie_hectare',
       'superficie_km2', 'densite', 'altitude_moyenne', 'altitude_minimale',
       'altitude_maximale', 'latitude_mairie', 'longitude_mairie',
       'latitude_centre', 'longitude_centre', 'grille_densite', 'gentile',
       'url_wikipedia', 'url_villedereve'],
      dtype='object')

In [41]:
# Nombre de valeurs non vides par ligne
nb_valeurs = communes.notna().sum(axis=1)

# Lignes avec très peu de colonnes remplies
lignes_suspectes = communes[nb_valeurs <= 3]

display(lignes_suspectes)

Empty DataFrame
Columns: [Unnamed: 0, code_insee, nom_standard, nom_sans_pronom, nom_a, nom_de, nom_sans_accent, nom_standard_majuscule, typecom, typecom_texte, reg_code, reg_nom, dep_code, dep_nom, canton_code, canton_nom, epci_code, epci_nom, academie_code, academie_nom, code_postal, codes_postaux, zone_emploi, code_insee_centre_zone_emploi, population, superficie_hectare, superficie_km2, densite, altitude_moyenne, altitude_minimale, altitude_maximale, latitude_mairie, longitude_mairie, latitude_centre, longitude_centre, grille_densite, gentile, url_wikipedia, url_villedereve]
Index: []

[0 rows x 39 columns]

In [ ]:
incendie_15_24 = pd.read_csv("data/raw/Incendies_2015_2024.csv", sep=";", skiprows=3)

In [ ]:
# Nombre de valeurs non vides par ligne
nb_valeurs = incendie_15_24.notna().sum(axis=1)

# Lignes avec très peu de colonnes remplies
lignes_suspectes = incendie_15_24[nb_valeurs <= 3]

display(lignes_suspectes)

Empty DataFrame
Columns: [Année, Numéro, Département, Code INSEE, Nom de la commune, Date de première alerte, Surface parcourue (m2), Surface forêt (m2), Surface maquis garrigues (m2), Autres surfaces naturelles hors forêt (m2), Surfaces agricoles (m2), Autres surfaces (m2), Surface autres terres boisées (m2), Surfaces non boisées naturelles (m2), Surfaces non boisées artificialisées (m2), Surfaces non boisées (m2), Précision des surfaces, Type de peuplement, Nature, Décès ou bâtiments touchés, Nombre de décès, Nombre de bâtiments totalement détruits, Nombre de bâtiments partiellement détruits, Précision de la donnée]
Index: []

[0 rows x 24 columns]

In [36]:
incendie_15_24.head()

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Surface parcourue (m2),Surface forêt (m2),Surface maquis garrigues (m2),Autres surfaces naturelles hors forêt (m2),...,Surfaces non boisées artificialisées (m2),Surfaces non boisées (m2),Précision des surfaces,Type de peuplement,Nature,Décès ou bâtiments touchés,Nombre de décès,Nombre de bâtiments totalement détruits,Nombre de bâtiments partiellement détruits,Précision de la donnée
0,2015,5769,66,66100,Llo,2015-01-01 00:09:00,5000,5000.0,NaN,NaN,...,NaN,NaN,NaN,4.0,Involontaire (particulier),NaN,NaN,NaN,NaN,NaN
1,2015,6760,07,07176,Planzolles,2015-01-01 13:13:00,10000,NaN,10000.0,NaN,...,NaN,NaN,NaN,1.0,Involontaire (particulier),NaN,NaN,NaN,NaN,NaN
2,2015,12057,2A,2A362,Zonza,2015-01-01 15:16:00,4000,NaN,4000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,6978,34,34260,Saint-Gervais-sur-Mare,2015-01-02 14:13:00,6450,6450.0,NaN,NaN,...,NaN,NaN,NaN,3.0,Involontaire (travaux),NaN,NaN,NaN,NaN,NaN
4,2015,2,12,12270,Sévérac-le-Château,2015-01-02 19:19:00,50,0.0,NaN,50.0,...,0.0,0.0,Estimées,NaN,Involontaire (particulier),NaN,NaN,NaN,NaN,NaN

In [7]:
incendie_15_24.columns

Index(['Année', 'Numéro', 'Département', 'Code INSEE', 'Nom de la commune',
       'Date de première alerte', 'Surface parcourue (m2)',
       'Surface forêt (m2)', 'Surface maquis garrigues (m2)',
       'Autres surfaces naturelles hors forêt (m2)', 'Surfaces agricoles (m2)',
       'Autres surfaces (m2)', 'Surface autres terres boisées (m2)',
       'Surfaces non boisées naturelles (m2)',
       'Surfaces non boisées artificialisées (m2)',
       'Surfaces non boisées (m2)', 'Précision des surfaces',
       'Type de peuplement', 'Nature', 'Décès ou bâtiments touchés',
       'Nombre de décès', 'Nombre de bâtiments totalement détruits',
       'Nombre de bâtiments partiellement détruits', 'Précision de la donnée'],
      dtype='object')

In [8]:
incendie_15_24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27862 entries, 0 to 27861
Data columns (total 24 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Année                                       27862 non-null  int64
 1   Numéro                                      27862 non-null  int64
 2   Département                                 27862 non-null  object
 3   Code INSEE                                  27862 non-null  object
 4   Nom de la commune                           27835 non-null  object
 5   Date de première alerte                     27862 non-null  object
 6   Surface parcourue (m2)                      27862 non-null  int64
 7   Surface forêt (m2)                          23885 non-null  float64
 8   Surface maquis garrigues (m2)               12173 non-null  float64
 9   Autres surfaces naturelles hors forêt (m2)  17948 non-null  float64
 10  Surfaces agricoles (m2)                     4067 non-null   float64
 11  Autres surfaces (m2)                        4051 non-null   float64
 12  Surface autres terres boisées (m2)          9969 non-null   float64
 13  Surfaces non boisées naturelles (m2)        7449 non-null   float64
 14  Surfaces non boisées artificialisées (m2)   7251 non-null   float64
 15  Surfaces non boisées (m2)                   14821 non-null  float64
 16  Précision des surfaces                      11932 non-null  object
 17  Type de peuplement                          10202 non-null  float64
 18  Nature                                      13169 non-null  object
 19  Décès ou bâtiments touchés                  4988 non-null   object
 20  Nombre de décès                             866 non-null    float64
 21  Nombre de bâtiments totalement détruits     867 non-null    float64
 22  Nombre de bâtiments partiellement détruits  866 non-null    float64
 23  Précision de la donnée                      895 non-null    object
dtypes: float64(13), int64(3), object(8)
memory usage: 5.1+ MB

In [9]:
incendie_15_24.isna().sum()

Année                                             0
Numéro                                            0
Département                                       0
Code INSEE                                        0
Nom de la commune                                27
Date de première alerte                           0
Surface parcourue (m2)                            0
Surface forêt (m2)                             3977
Surface maquis garrigues (m2)                 15689
Autres surfaces naturelles hors forêt (m2)     9914
Surfaces agricoles (m2)                       23795
Autres surfaces (m2)                          23811
Surface autres terres boisées (m2)            17893
Surfaces non boisées naturelles (m2)          20413
Surfaces non boisées artificialisées (m2)     20611
Surfaces non boisées (m2)                     13041
Précision des surfaces                        15930
Type de peuplement                            17660
Nature                                        14693
Décès ou bâtiments touchés                    22874
Nombre de décès                               26996
Nombre de bâtiments totalement détruits       26995
Nombre de bâtiments partiellement détruits    26996
Précision de la donnée                        26967
dtype: int64

In [10]:
incendie_73_82 = pd.read_csv("data/raw/Incendies_1973_1982.csv", sep=";", skiprows=3)
incendie_83_92 = pd.read_csv("data/raw/Incendies_1983_1992.csv", sep=";", skiprows=3)
incendie_93_03 = pd.read_csv("data/raw/Incendies_1993_2003.csv", sep=";", skiprows=3)
incendie_04_14 = pd.read_csv("data/raw/Incendies_2004_2014.csv", sep=";", skiprows=6)

In [11]:
incendie_93_03.head()

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Surface parcourue (m2),Surface forêt (m2),Surface maquis garrigues (m2),Autres surfaces naturelles hors forêt (m2),...,Surfaces non boisées artificialisées (m2),Surfaces non boisées (m2),Précision des surfaces,Type de peuplement,Nature,Décès ou bâtiments touchés,Nombre de décès,Nombre de bâtiments totalement détruits,Nombre de bâtiments partiellement détruits,Précision de la donnée
0,1993,38,06,06022,Bouyon,1993-01-01 00:30:00,200,94,96,0.0,...,NaN,10.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1993,39,06,06163,Tende,1993-01-01 00:37:00,200,94,96,0.0,...,NaN,10.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1993,40,06,06132,Saorge,1993-01-01 09:20:00,800000,376000,384000,0.0,...,NaN,40000.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1993,20,05,05058,Freissinières,1993-01-02 14:16:00,50,24,24,0.0,...,NaN,2.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1993,41,06,06122,Saint-Jeannet,1993-01-04 17:40:00,50,24,24,0.0,...,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
bdiff = pd.concat([incendie_73_82, incendie_83_92, incendie_93_03, incendie_04_14, incendie_15_24], ignore_index=True)

In [42]:
nb_valeurs = bdiff.notna().sum(axis=1)

lignes_suspectes = bdiff[nb_valeurs <= 3]

display(lignes_suspectes)

print("Nombre de lignes suspectes :", len(lignes_suspectes))

Empty DataFrame
Columns: [Année, Numéro, Département, Code INSEE, Nom de la commune, Date de première alerte, Surface parcourue (m2), Surface forêt (m2), Surface maquis garrigues (m2), Autres surfaces naturelles hors forêt (m2), Surfaces agricoles (m2), Autres surfaces (m2), Surface autres terres boisées (m2), Surfaces non boisées naturelles (m2), Surfaces non boisées artificialisées (m2), Surfaces non boisées (m2), Précision des surfaces, Type de peuplement, Nature, Décès ou bâtiments touchés, Nombre de décès, Nombre de bâtiments totalement détruits, Nombre de bâtiments partiellement détruits, Précision de la donnée]
Index: []

[0 rows x 24 columns]

Nombre de lignes suspectes : 0

In [13]:
bdiff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140248 entries, 0 to 140247
Data columns (total 24 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   Année                                       140248 non-null  int64
 1   Numéro                                      140248 non-null  int64
 2   Département                                 140248 non-null  object
 3   Code INSEE                                  140248 non-null  object
 4   Nom de la commune                           140221 non-null  object
 5   Date de première alerte                     140248 non-null  object
 6   Surface parcourue (m2)                      140248 non-null  int64
 7   Surface forêt (m2)                          135598 non-null  float64
 8   Surface maquis garrigues (m2)               116724 non-null  float64
 9   Autres surfaces naturelles hors forêt (m2)  104818 non-null  float64
 10  Surfaces agricoles (m2)                     4067 non-null    float64
 11  Autres surfaces (m2)                        4051 non-null    float64
 12  Surface autres terres boisées (m2)          17028 non-null   float64
 13  Surfaces non boisées naturelles (m2)        10695 non-null   float64
 14  Surfaces non boisées artificialisées (m2)   10428 non-null   float64
 15  Surfaces non boisées (m2)                   109486 non-null  float64
 16  Précision des surfaces                      13356 non-null   object
 17  Type de peuplement                          77515 non-null   float64
 18  Nature                                      50162 non-null   object
 19  Décès ou bâtiments touchés                  4988 non-null    object
 20  Nombre de décès                             866 non-null     float64
 21  Nombre de bâtiments totalement détruits     867 non-null     float64
 22  Nombre de bâtiments partiellement détruits  866 non-null     float64
 23  Précision de la donnée                      1215 non-null    object
dtypes: float64(13), int64(3), object(8)
memory usage: 25.7+ MB

In [26]:
bdiff.Nature.unique()

array([nan, 'Involontaire (travaux)', 'Malveillance', 'Accidentelle',
       'Involontaire (particulier)', 'Naturelle'], dtype=object)

In [14]:
bdiff.head()

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Surface parcourue (m2),Surface forêt (m2),Surface maquis garrigues (m2),Autres surfaces naturelles hors forêt (m2),...,Surfaces non boisées artificialisées (m2),Surfaces non boisées (m2),Précision des surfaces,Type de peuplement,Nature,Décès ou bâtiments touchés,Nombre de décès,Nombre de bâtiments totalement détruits,Nombre de bâtiments partiellement détruits,Précision de la donnée
0,1973,8,06,06060,Falicon,1973-01-09 13:50:00,10000,4700.0,4800.0,0.0,...,NaN,500.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1973,1871,83,83038,Châteaudouble,1973-01-28 13:25:00,30000,14100.0,14400.0,0.0,...,NaN,1500.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1973,1872,83,83078,Moissac-Bellevue,1973-01-29 11:15:00,6000,2820.0,2880.0,0.0,...,NaN,300.0,NaN,1.0,Involontaire (travaux),NaN,NaN,NaN,NaN,NaN
3,1973,1639,34,34163,Montarnaud,1973-01-29 13:00:00,100000,47000.0,48000.0,0.0,...,NaN,5000.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1973,9,06,06012,Beausoleil,1973-01-29 15:00:00,40000,18800.0,19200.0,0.0,...,NaN,2000.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
bdiff.duplicated().sum()

np.int64(0)

In [28]:
communes.duplicated().sum()

np.int64(0)

In [15]:
bdiff.to_csv("data/proccessed/bdiff.csv")

In [16]:
bdiff["Code INSEE"].dtype

dtype('O')

In [17]:
communes["code_insee"].dtype

dtype('O')

le code insee est du meme type

In [18]:
print(bdiff["Code INSEE"].head())
print(communes["code_insee"].head())

0    06060
1    83038
2    83078
3    34163
4    06012
Name: Code INSEE, dtype: object
0    01001
1    01002
2    01004
3    01005
4    01006
Name: code_insee, dtype: object

In [25]:
correspondance = bdiff["Code INSEE"].isin(communes["code_insee"])
print(correspondance.value_counts())
print(correspondance.mean()*1001)

Code INSEE
True     139338
False       910
Name: count, dtype: int64
994.505005418972

139338  lignes  dont le Code INSEE existe aussi dans communes
910 lignes dont le Code INSEE n'existe pas dans communes. 
soit une un pourcentage de 95%

In [20]:
bdiff_geo = bdiff.merge(communes, left_on= "Code INSEE", right_on="code_insee", how="left") # j'ai fait une jointure gauche pour garder toutesz les lignes d'incendies

In [21]:
bdiff_geo.head()

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Surface parcourue (m2),Surface forêt (m2),Surface maquis garrigues (m2),Autres surfaces naturelles hors forêt (m2),...,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,gentile,url_wikipedia,url_villedereve
0,1973,8,06,06060,Falicon,1973-01-09 13:50:00,10000,4700.0,4800.0,0.0,...,103.0,581.0,43.752,7.266,43.752,7.266,Ceintures urbaines,Faliconnais,https://fr.wikipedia.org/wiki/fr:Falicon,https://villedereve.fr/ville/06060-falicon
1,1973,1871,83,83038,Châteaudouble,1973-01-28 13:25:00,30000,14100.0,14400.0,0.0,...,210.0,1039.0,43.624,6.436,43.624,6.436,Rural à habitat dispersé,"Châteaudoublains, Châteaudoublaines",https://fr.wikipedia.org/wiki/fr:Châteaudouble...,https://villedereve.fr/ville/83038-chateaudouble
2,1973,1872,83,83078,Moissac-Bellevue,1973-01-29 11:15:00,6000,2820.0,2880.0,0.0,...,430.0,982.0,43.647,6.167,43.647,6.167,Rural à habitat dispersé,NaN,https://fr.wikipedia.org/wiki/fr:Moissac-Bellevue,https://villedereve.fr/ville/83078-moissac-bel...
3,1973,1639,34,34163,Montarnaud,1973-01-29 13:00:00,100000,47000.0,48000.0,0.0,...,105.0,319.0,43.647,3.700,43.647,3.700,Bourgs ruraux,Montarnéens,https://fr.wikipedia.org/wiki/fr:Montarnaud,https://villedereve.fr/ville/34163-montarnaud
4,1973,9,06,06012,Beausoleil,1973-01-29 15:00:00,40000,18800.0,19200.0,0.0,...,40.0,621.0,43.748,7.422,43.748,7.422,Centres urbains intermédiaires,Beausoleillois,https://fr.wikipedia.org/wiki/fr:Beausoleil (A...,https://villedereve.fr/ville/06012-beausoleil

In [23]:
print(len(bdiff))
print(len(bdiff_geo))

140248
140248

In [24]:
bdiff_geo.to_csv("data/proccessed/bdiffgeo.csv")

resumé du travail fait:

-Collecte des données BDIFF et du référentiel des communes INSEE
-Lecture et contrôle de la structure des données(colonnes;....)
-Concaténation des différents fichiers BDIFF
-Vérification des codes INSEE et de leur correspondance entre les deux bases
-Jointure des données BDIFF avec le référentiel des communes

In [70]:
bdiff.shape

(140248, 24)

In [71]:
communes.shape

(34990, 39)

In [69]:
bdiff_geo.shape

(140248, 63)

In [72]:
bdiff_geo.duplicated().sum()

np.int64(0)

pas de doublons de ligne

In [74]:
bdiff_geo.isna().sum()

Année                    0
Numéro                   0
Département              0
Code INSEE               0
Nom de la commune       27
                     ...
longitude_centre      1745
grille_densite         915
gentile              33041
url_wikipedia          948
url_villedereve        910
Length: 63, dtype: int64

les valeurs manquantes dans chaque colones ca peut aussi venir de la jointure

# id ville , non ville; id locali, latitude, longi; id inceendie, date superficie. ( situer, avoir lieu, affecte).   ville()    , un tableau avec les 30 derniers annees, timeline et geolicasation (le produiir. cartesien).  (date et geocommunes  et chronologie  avec des id communes  et un event de 1 ou 0 pour une jointure gauche avec les incendies ) identifier les coudes a la fin de l'EDEA

In [43]:
import sqlite3

In [ ]:
# Le fichier incendies.db sera créé dans le dossier database
conn = sqlite3.connect("database/incendies.db")

In [46]:
# On crée une table SQL appelée "incendies"
# Elle contient pour l'instant toutes les colonnes de bdiff_geo
# Donc ici on crée une première version "brute" de la base SQL

bdiff_geo.to_sql(
    "incendies",      
    conn,             
    if_exists="replace",  
    index=False       
)
conn.close()

In [47]:
conn = sqlite3.connect("database/incendies.db")

In [48]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database/incendies.db")

pd.read_sql_query(
    "SELECT COUNT(*) AS nombre_incendies FROM incendies",
    conn
)

   nombre_incendies
0            140248

In [49]:
pd.read_sql_query(
    "SELECT * FROM incendies LIMIT 5",
    conn
)

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Surface parcourue (m2),Surface forêt (m2),Surface maquis garrigues (m2),Autres surfaces naturelles hors forêt (m2),...,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,gentile,url_wikipedia,url_villedereve
0,1973,8,06,06060,Falicon,1973-01-09 13:50:00,10000,4700.0,4800.0,0.0,...,103.0,581.0,43.752,7.266,43.752,7.266,Ceintures urbaines,Faliconnais,https://fr.wikipedia.org/wiki/fr:Falicon,https://villedereve.fr/ville/06060-falicon
1,1973,1871,83,83038,Châteaudouble,1973-01-28 13:25:00,30000,14100.0,14400.0,0.0,...,210.0,1039.0,43.624,6.436,43.624,6.436,Rural à habitat dispersé,"Châteaudoublains, Châteaudoublaines",https://fr.wikipedia.org/wiki/fr:Châteaudouble...,https://villedereve.fr/ville/83038-chateaudouble
2,1973,1872,83,83078,Moissac-Bellevue,1973-01-29 11:15:00,6000,2820.0,2880.0,0.0,...,430.0,982.0,43.647,6.167,43.647,6.167,Rural à habitat dispersé,None,https://fr.wikipedia.org/wiki/fr:Moissac-Bellevue,https://villedereve.fr/ville/83078-moissac-bel...
3,1973,1639,34,34163,Montarnaud,1973-01-29 13:00:00,100000,47000.0,48000.0,0.0,...,105.0,319.0,43.647,3.700,43.647,3.700,Bourgs ruraux,Montarnéens,https://fr.wikipedia.org/wiki/fr:Montarnaud,https://villedereve.fr/ville/34163-montarnaud
4,1973,9,06,06012,Beausoleil,1973-01-29 15:00:00,40000,18800.0,19200.0,0.0,...,40.0,621.0,43.748,7.422,43.748,7.422,Centres urbains intermédiaires,Beausoleillois,https://fr.wikipedia.org/wiki/fr:Beausoleil (A...,https://villedereve.fr/ville/06012-beausoleil

In [50]:
conn.close()

In [52]:
for i, col in enumerate(bdiff_geo.columns):
    print(i, col)

0 Année
1 Numéro
2 Département
3 Code INSEE
4 Nom de la commune
5 Date de première alerte
6 Surface parcourue (m2)
7 Surface forêt (m2)
8 Surface maquis garrigues (m2)
9 Autres surfaces naturelles hors forêt (m2)
10 Surfaces agricoles (m2)
11 Autres surfaces (m2)
12 Surface autres terres boisées (m2)
13 Surfaces non boisées naturelles (m2)
14 Surfaces non boisées artificialisées (m2)
15 Surfaces non boisées (m2)
16 Précision des surfaces
17 Type de peuplement
18 Nature
19 Décès ou bâtiments touchés
20 Nombre de décès
21 Nombre de bâtiments totalement détruits
22 Nombre de bâtiments partiellement détruits
23 Précision de la donnée
24 Unnamed: 0
25 code_insee
26 nom_standard
27 nom_sans_pronom
28 nom_a
29 nom_de
30 nom_sans_accent
31 nom_standard_majuscule
32 typecom
33 typecom_texte
34 reg_code
35 reg_nom
36 dep_code
37 dep_nom
38 canton_code
39 canton_nom
40 epci_code
41 epci_nom
42 academie_code
43 academie_nom
44 code_postal
45 codes_postaux
46 zone_emploi
47 code_insee_centre_zone_emploi
48 population
49 superficie_hectare
50 superficie_km2
51 densite
52 altitude_moyenne
53 altitude_minimale
54 altitude_maximale
55 latitude_mairie
56 longitude_mairie
57 latitude_centre
58 longitude_centre
59 grille_densite
60 gentile
61 url_wikipedia
62 url_villedereve

In [54]:

# DIAGNOSTIC INITIAL DE LA BASE BDIFF
# Objectif : vérifier la structure, les types, les doublons
# et les valeurs manquantes avant le nettoyage et la jointure


print("BDIFF shape :", bdiff.shape)

print("\nColonnes :")
for i, col in enumerate(bdiff.columns):
    print(i, col)

print("\nTypes :")
print(bdiff.dtypes)

print("\nDoublons :", bdiff.duplicated().sum())

print("\nValeurs manquantes :")
print(bdiff.isna().sum().sort_values(ascending=False))

BDIFF shape : (140248, 24)

Colonnes :
0 Année
1 Numéro
2 Département
3 Code INSEE
4 Nom de la commune
5 Date de première alerte
6 Surface parcourue (m2)
7 Surface forêt (m2)
8 Surface maquis garrigues (m2)
9 Autres surfaces naturelles hors forêt (m2)
10 Surfaces agricoles (m2)
11 Autres surfaces (m2)
12 Surface autres terres boisées (m2)
13 Surfaces non boisées naturelles (m2)
14 Surfaces non boisées artificialisées (m2)
15 Surfaces non boisées (m2)
16 Précision des surfaces
17 Type de peuplement
18 Nature
19 Décès ou bâtiments touchés
20 Nombre de décès
21 Nombre de bâtiments totalement détruits
22 Nombre de bâtiments partiellement détruits
23 Précision de la donnée

Types :
Année                                           int64
Numéro                                          int64
Département                                    object
Code INSEE                                     object
Nom de la commune                              object
Date de première alerte                        object
Surface parcourue (m2)                          int64
Surface forêt (m2)                            float64
Surface maquis garrigues (m2)                 float64
Autres surfaces naturelles hors forêt (m2)    float64
Surfaces agricoles (m2)                       float64
Autres surfaces (m2)                          float64
Surface autres terres boisées (m2)            float64
Surfaces non boisées naturelles (m2)          float64
Surfaces non boisées artificialisées (m2)     float64
Surfaces non boisées (m2)                     float64
Précision des surfaces                         object
Type de peuplement                            float64
Nature                                         object
Décès ou bâtiments touchés                     object
Nombre de décès                               float64
Nombre de bâtiments totalement détruits       float64
Nombre de bâtiments partiellement détruits    float64
Précision de la donnée                         object
dtype: object

Doublons : 0

Valeurs manquantes :
Nombre de bâtiments partiellement détruits    139382
Nombre de décès                               139382
Nombre de bâtiments totalement détruits       139381
Précision de la donnée                        139033
Autres surfaces (m2)                          136197
Surfaces agricoles (m2)                       136181
Décès ou bâtiments touchés                    135260
Surfaces non boisées artificialisées (m2)     129820
Surfaces non boisées naturelles (m2)          129553
Précision des surfaces                        126892
Surface autres terres boisées (m2)            123220
Nature                                         90086
Type de peuplement                             62733
Autres surfaces naturelles hors forêt (m2)     35430
Surfaces non boisées (m2)                      30762
Surface maquis garrigues (m2)                  23524
Surface forêt (m2)                              4650
Nom de la commune                                 27
Surface parcourue (m2)                             0
Date de première alerte                            0
Numéro                                             0
Année                                              0
Département                                        0
Code INSEE                                         0
dtype: int64

In [ ]:

# NETTOYAGE DES TYPES - BDIFF


bdiff["Date de première alerte"] = pd.to_datetime(
    bdiff["Date de première alerte"],
    errors="coerce"
)

print(bdiff.dtypes)

Année                                                  int64
Numéro                                                 int64
Département                                           object
Code INSEE                                            object
Nom de la commune                                     object
Date de première alerte                       datetime64[ns]
Surface parcourue (m2)                                 int64
Surface forêt (m2)                                   float64
Surface maquis garrigues (m2)                        float64
Autres surfaces naturelles hors forêt (m2)           float64
Surfaces agricoles (m2)                              float64
Autres surfaces (m2)                                 float64
Surface autres terres boisées (m2)                   float64
Surfaces non boisées naturelles (m2)                 float64
Surfaces non boisées artificialisées (m2)            float64
Surfaces non boisées (m2)                            float64
Précision des surfaces                                object
Type de peuplement                                   float64
Nature                                                object
Décès ou bâtiments touchés                            object
Nombre de décès                                      float64
Nombre de bâtiments totalement détruits              float64
Nombre de bâtiments partiellement détruits           float64
Précision de la donnée                                object
dtype: object

In [56]:
colonnes_numeriques = [
    "Surface parcourue (m2)",
    "Surface forêt (m2)",
    "Surface maquis garrigues (m2)",
    "Autres surfaces naturelles hors forêt (m2)",
    "Surfaces agricoles (m2)",
    "Autres surfaces (m2)",
    "Surface autres terres boisées (m2)",
    "Surfaces non boisées naturelles (m2)",
    "Surfaces non boisées artificialisées (m2)",
    "Surfaces non boisées (m2)",
    "Nombre de décès",
    "Nombre de bâtiments totalement détruits",
    "Nombre de bâtiments partiellement détruits"
]

for col in colonnes_numeriques:
    print(col, ":", (bdiff[col] < 0).sum(), "valeur(s) négative(s)")

Surface parcourue (m2) : 0 valeur(s) négative(s)
Surface forêt (m2) : 0 valeur(s) négative(s)
Surface maquis garrigues (m2) : 0 valeur(s) négative(s)
Autres surfaces naturelles hors forêt (m2) : 0 valeur(s) négative(s)
Surfaces agricoles (m2) : 0 valeur(s) négative(s)
Autres surfaces (m2) : 0 valeur(s) négative(s)
Surface autres terres boisées (m2) : 0 valeur(s) négative(s)
Surfaces non boisées naturelles (m2) : 0 valeur(s) négative(s)
Surfaces non boisées artificialisées (m2) : 0 valeur(s) négative(s)
Surfaces non boisées (m2) : 0 valeur(s) négative(s)
Nombre de décès : 0 valeur(s) négative(s)
Nombre de bâtiments totalement détruits : 0 valeur(s) négative(s)
Nombre de bâtiments partiellement détruits : 0 valeur(s) négative(s)

In [57]:
# RESUME DU NETTOYAGE INITIAL - BDIFF

# La base BDIFF contient 140 248 lignes et 24 colonnes.

# Vérifications réalisées :
# - contrôle de la structure générale de la base ;
# - contrôle des noms de colonnes ;
# - contrôle des types de données ;
# - contrôle des doublons complets : aucun doublon détecté ;
# - contrôle des valeurs manquantes ;
# - conversion de `Date de première alerte` au format datetime ;
# - contrôle des valeurs négatives sur les variables numériques :
#   aucune valeur négative détectée ;
# - contrôle des lignes parasites ou incohérentes :
#   aucune ligne suspecte détectée.

# Décisions prises :
# - aucune ligne n'est supprimée à ce stade ;
# - aucune colonne métier de la BDIFF n'est supprimée ;
# - les valeurs manquantes sont conservées pour être analysées plus tard lors de l'EDA ;
# - les codes INSEE et départements sont conservés comme variables texte.

# Conclusion :
# La BDIFF est structurellement cohérente et peut être utilisée pour la suite
# du travail de consolidation avec la base des communes.

In [58]:
# DIAGNOSTIC INITIAL - COMMUNES

print("COMMUNES shape :", communes.shape)

print("\nColonnes :")
for i, col in enumerate(communes.columns):
    print(i, col)

print("\nTypes :")
print(communes.dtypes)

print("\nDoublons complets :", communes.duplicated().sum())

print("\nValeurs manquantes :")
print(communes.isna().sum().sort_values(ascending=False))

print("\nCodes INSEE dupliqués :")
print(communes["code_insee"].duplicated().sum())

print("\nCodes INSEE manquants :")
print(communes["code_insee"].isna().sum())

COMMUNES shape : (34990, 39)

Colonnes :
0 Unnamed: 0
1 code_insee
2 nom_standard
3 nom_sans_pronom
4 nom_a
5 nom_de
6 nom_sans_accent
7 nom_standard_majuscule
8 typecom
9 typecom_texte
10 reg_code
11 reg_nom
12 dep_code
13 dep_nom
14 canton_code
15 canton_nom
16 epci_code
17 epci_nom
18 academie_code
19 academie_nom
20 code_postal
21 codes_postaux
22 zone_emploi
23 code_insee_centre_zone_emploi
24 population
25 superficie_hectare
26 superficie_km2
27 densite
28 altitude_moyenne
29 altitude_minimale
30 altitude_maximale
31 latitude_mairie
32 longitude_mairie
33 latitude_centre
34 longitude_centre
35 grille_densite
36 gentile
37 url_wikipedia
38 url_villedereve

Types :
Unnamed: 0                         int64
code_insee                        object
nom_standard                      object
nom_sans_pronom                   object
nom_a                             object
nom_de                            object
nom_sans_accent                   object
nom_standard_majuscule            object
typecom                           object
typecom_texte                     object
reg_code                           int64
reg_nom                           object
dep_code                          object
dep_nom                           object
canton_code                       object
canton_nom                        object
epci_code                         object
epci_nom                          object
academie_code                      int64
academie_nom                      object
code_postal                        int64
codes_postaux                     object
zone_emploi                      float64
code_insee_centre_zone_emploi     object
population                         int64
superficie_hectare                 int64
superficie_km2                     int64
densite                          float64
altitude_moyenne                   int64
altitude_minimale                float64
altitude_maximale                float64
latitude_mairie                  float64
longitude_mairie                 float64
latitude_centre                  float64
longitude_centre                 float64
grille_densite                    object
gentile                           object
url_wikipedia                     object
url_villedereve                   object
dtype: object

Doublons complets : 0

Valeurs manquantes :
gentile                          10914
canton_code                        145
canton_nom                         145
code_insee_centre_zone_emploi      129
grille_densite                      58
url_wikipedia                       54
epci_nom                            45
zone_emploi                         45
latitude_centre                     19
longitude_centre                    19
densite                             17
codes_postaux                       16
nom_standard                         0
Unnamed: 0                           0
code_insee                           0
nom_sans_accent                      0
nom_de                               0
nom_a                                0
nom_sans_pronom                      0
dep_nom                              0
nom_standard_majuscule               0
typecom_texte                        0
typecom                              0
academie_nom                         0
code_postal                          0
epci_code                            0
academie_code                        0
reg_code                             0
reg_nom                              0
dep_code                             0
superficie_hectare                   0
altitude_maximale                    0
altitude_minimale                    0
altitude_moyenne                     0
superficie_km2                       0
population                           0
longitude_mairie                     0
latitude_mairie                      0
url_villedereve                      0
dtype: int64

Codes INSEE dupliqués :
0

Codes INSEE manquants :
0

In [59]:
# RESUME DU DIAGNOSTIC INITIAL - COMMUNES

# La base communes contient 34 990 lignes et 39 colonnes.

# Vérifications réalisées :
# - aucun doublon complet détecté ;
# - aucun code INSEE manquant ;
# - aucun code INSEE dupliqué ;
# - le code INSEE peut donc être utilisé comme identifiant unique des communes ;
# - les principales variables géographiques et démographiques
#   (population, superficie, densité, altitude, coordonnées) sont disponibles ;
# - certaines colonnes contiennent des valeurs manquantes, notamment `gentile`,
#   `canton_code`, `canton_nom`, `zone_emploi`, `latitude_centre`
#   et `longitude_centre`.

# Observations :
# - `Unnamed: 0` correspond probablement à un ancien index ;
# - certaines colonnes comme `gentile`, les URL et plusieurs variantes
#   du nom de commune semblent peu utiles pour l'objectif du projet ;
# - ces colonnes ne sont pas supprimées à ce stade : leur suppression
#   sera décidée lors de la préparation de la base SQL finale ;
# - `code_postal` devra être considéré comme une variable texte et non
#   comme une variable numérique.

# Conclusion :
# La base communes est globalement cohérente et peut servir de référentiel
# géographique pour la consolidation avec la BDIFF.

In [60]:
# ANALYSE DES CODES INSEE SANS CORRESPONDANCE

sans_correspondance = bdiff_geo[
    bdiff_geo["code_insee"].isna()
].copy()

print("Nombre de lignes sans correspondance :", len(sans_correspondance))

print(
    "Nombre de codes INSEE BDIFF distincts sans correspondance :",
    sans_correspondance["Code INSEE"].nunique()
)

print("\nRépartition par année :")
print(
    sans_correspondance["Année"]
    .value_counts()
    .sort_index()
)

Nombre de lignes sans correspondance : 910
Nombre de codes INSEE BDIFF distincts sans correspondance : 205

Répartition par année :
Année
1973     7
1974     8
1975     6
1976    19
1977     3
1978    19
1979    29
1980    11
1981    15
1982     8
1983     8
1984    11
1985    33
1986    15
1987     9
1988    10
1989    28
1990    14
1991    11
1992     8
1993    16
1994    27
1995    11
1996    10
1997     8
1998    11
1999     3
2000     8
2001     5
2002    14
2003    45
2004    18
2005    13
2006    26
2007    24
2008    26
2009    43
2010    40
2011    49
2012    28
2013    12
2014    16
2015    39
2016    25
2017    29
2018    20
2019    35
2020    10
2021     6
2022    21
Name: count, dtype: int64

In [61]:
# CODES INSEE SANS CORRESPONDANCE - DETAIL

codes_non_trouves = (
    sans_correspondance[
        ["Code INSEE", "Nom de la commune", "Département", "Année"]
    ]
    .drop_duplicates()
    .sort_values(["Code INSEE", "Année"])
)

display(codes_non_trouves)

       Code INSEE           Nom de la commune Département  Année
96218       01097                   Chavornay          01   2008
106734      01316                      Pugieu          01   2012
107216      04100                      Larche          04   2012
63949       04198     Saint-Vincent-les-Forts          04   1995
100025      04198     Saint-Vincent-les-Forts          04   2009
...           ...                         ...         ...    ...
120603      86166            Montreuil-Bonnin          86   2017
122625      86166            Montreuil-Bonnin          86   2018
117554      86278                        Vaux          86   2016
125743      87173               Saint-Pardoux          87   2019
123747      87184  Saint-Symphorien-sur-Couze          87   2019

[703 rows x 4 columns]

In [62]:
resume_codes = (
    sans_correspondance
    .groupby(["Code INSEE", "Nom de la commune"])
    .agg(
        nb_incendies=("Code INSEE", "size"),
        premiere_annee=("Année", "min"),
        derniere_annee=("Année", "max")
    )
    .sort_values("nb_incendies", ascending=False)
)

display(resume_codes.head(30))

,,nb_incendies,premiere_annee,derniere_annee
Code INSEE,Nom de la commune,,,
30190,Notre-Dame-de-la-Rouvière,51,1974,2019
07016,Asperjoc,42,1973,2017
48022,Bédouès,42,1976,2020
48040,Chasseradès,34,1978,2019
48172,Saint-Maurice-de-Ventalon,33,1976,2020
48162,Saint-Julien-d'Arpaon,28,1976,2020
48066,Fraissinet-de-Lozère,25,1978,2019
83999,Commune inconnue,24,1979,2011
48049,Chirac,21,1979,2012
48134,Saint-Andéol-de-Clerguemort,17,1974,2020
48122,Quézac,16,1980,2019
48195,Les Vignes,15,1981,2020
07256,Saint-Julien-Labrousse,15,1975,2017
48076,Javols,14,1987,2020
07252,Saint-Julien-Boutières,13,1973,2009
48186,La Salle-Prunet,13,1977,2014
48180,Saint-Rome-de-Dolan,11,1985,2018
48078,Lachamp,10,1986,2020
46287,Saint-Paul-de-Loubressac,10,2006,2016
48101,Montbrun,10,1976,2011
48184,Saint-Symphorien,10,1987,2013
11050,Brenac,9,1973,2019
26354,Treschenu-Creyers,9,1996,2017
33267,Marcillac,9,2006,2016
48154,Saint-Georges-de-Lévéjac,9,1986,2018
48164,Saint-Julien-du-Tournel,8,1981,2003
24093,Cercles,8,2006,2012
11298,Pradelles-en-Val,8,1973,2010
30157,Mars,7,1973,1996
46067,Cazillac,7,2008,2018

In [63]:
import pandas as pd

mouvements = pd.read_csv(
    "data/raw/v_mvt_commune_2026.csv",
    dtype=str
)

print(mouvements.shape)
print(mouvements.columns.tolist())

(13734, 14)
['MOD', 'DATE_EFF', 'TYPECOM_AV', 'COM_AV', 'TNCC_AV', 'NCC_AV', 'NCCENR_AV', 'LIBELLE_AV', 'TYPECOM_AP', 'COM_AP', 'TNCC_AP', 'NCC_AP', 'NCCENR_AP', 'LIBELLE_AP']

In [64]:
# VERIFICATION DES CODES INSEE NON APPARIES DANS L'HISTORIQUE INSEE

mouvements["COM_AV"] = mouvements["COM_AV"].str.strip()
mouvements["COM_AP"] = mouvements["COM_AP"].str.strip()

sans_correspondance["Code INSEE"] = (
    sans_correspondance["Code INSEE"]
    .astype(str)
    .str.strip()
)

codes_non_apparies = (
    sans_correspondance["Code INSEE"]
    .dropna()
    .unique()
)

mouvements_trouves = mouvements[
    mouvements["COM_AV"].isin(codes_non_apparies)
].copy()

print(
    "Nombre de codes non appariés retrouvés dans l'historique INSEE :",
    mouvements_trouves["COM_AV"].nunique()
)

print(
    "Nombre total de codes non appariés :",
    len(codes_non_apparies)
)

Nombre de codes non appariés retrouvés dans l'historique INSEE : 202
Nombre total de codes non appariés : 205

In [65]:
# IDENTIFICATION DES CODES NON EXPLIQUES PAR L'HISTORIQUE INSEE

codes_retrouves = set(mouvements_trouves["COM_AV"].unique())

codes_non_expliques = [
    code for code in codes_non_apparies
    if code not in codes_retrouves
]

print("Codes restant à expliquer :", codes_non_expliques)

display(
    sans_correspondance[
        sans_correspondance["Code INSEE"].isin(codes_non_expliques)
    ][
        ["Code INSEE", "Nom de la commune", "Département", "Année"]
    ]
    .drop_duplicates()
    .sort_values(["Code INSEE", "Année"])
)

Codes restant à expliquer : ['83999', '66999', '06999']

       Code INSEE Nom de la commune Département  Année
37819       06999  Commune inconnue          06   1985
46868       06999  Commune inconnue          06   1989
18405       66999  Commune inconnue          66   1979
31192       66999  Commune inconnue          66   1983
16911       83999  Commune inconnue          83   1979
75798       83999  Commune inconnue          83   2000
84397       83999  Commune inconnue          83   2003
86513       83999  Commune inconnue          83   2004
90916       83999  Commune inconnue          83   2006
94529       83999  Commune inconnue          83   2007
97091       83999  Commune inconnue          83   2008
101647      83999  Commune inconnue          83   2010
103915      83999  Commune inconnue          83   2011

In [66]:
# NOMBRE D'INCENDIES EXPLIQUES PAR LES CHANGEMENTS ADMINISTRATIFS

lignes_expliquees = sans_correspondance[
    sans_correspondance["Code INSEE"].isin(codes_retrouves)
]

print(
    "Incendies associés à un ancien code retrouvé :",
    len(lignes_expliquees)
)

print(
    "Incendies restant sans explication :",
    len(sans_correspondance) - len(lignes_expliquees)
)

Incendies associés à un ancien code retrouvé : 875
Incendies restant sans explication : 35

In [67]:
# RATTACHEMENT DES ANCIENS CODES INSEE AUX COMMUNES ACTUELLES

# Nettoyage des codes INSEE

communes["code_insee"] = (
    communes["code_insee"]
    .astype(str)
    .str.strip()
)

mouvements["COM_AV"] = (
    mouvements["COM_AV"]
    .astype(str)
    .str.strip()
)

mouvements["COM_AP"] = (
    mouvements["COM_AP"]
    .astype(str)
    .str.strip()
)

sans_correspondance["Code INSEE"] = (
    sans_correspondance["Code INSEE"]
    .astype(str)
    .str.strip()
)


# Ensemble des codes INSEE présents dans le référentiel communal actuel

codes_actuels = set(
    communes["code_insee"]
    .dropna()
    .unique()
)


# Liste des codes INSEE BDIFF qui n'ont pas trouvé de correspondance

codes_non_apparies = (
    sans_correspondance["Code INSEE"]
    .dropna()
    .unique()
)


# Table simplifiée des changements de codes INSEE

passages = (
    mouvements[
        ["COM_AV", "COM_AP"]
    ]
    .dropna()
    .drop_duplicates()
)


# Vérification des anciens codes qui ont plusieurs codes après événement

plusieurs_destinations = (
    passages
    .groupby("COM_AV")["COM_AP"]
    .nunique()
)

plusieurs_destinations = plusieurs_destinations[
    plusieurs_destinations > 1
]

print(
    "Nombre d'anciens codes ayant plusieurs destinations :",
    len(plusieurs_destinations)
)


# Création du dictionnaire ancien code -> nouveau code

# Attention :
# on utilise ici uniquement les anciens codes qui ont une seule destination.
# Les cas complexes seront vérifiés séparément.

passages_uniques = (
    passages[
        passages["COM_AV"].isin(
            plusieurs_destinations.index
        ) == False
    ]
)

passage_dict = dict(
    zip(
        passages_uniques["COM_AV"],
        passages_uniques["COM_AP"]
    )
)


# Fonction permettant de suivre les changements administratifs
# jusqu'à retrouver un code présent dans le référentiel actuel

def trouver_code_actuel(code, max_etapes=20):

    code = str(code).strip()

    historique = [code]

    for _ in range(max_etapes):

        # Si le code existe dans le référentiel actuel,
        # on considère que la commune actuelle est retrouvée

        if code in codes_actuels:
            return code, historique, "retrouve"

        # Si le code a plusieurs destinations possibles,
        # on classe le cas comme complexe

        if code in plusieurs_destinations.index:
            return None, historique, "cas_complexe"

        # Si aucun changement n'est trouvé dans l'historique INSEE

        if code not in passage_dict:
            return None, historique, "non_retrouve"

        nouveau_code = passage_dict[code]

        # Protection contre une éventuelle boucle

        if nouveau_code in historique:
            return None, historique, "boucle"

        code = nouveau_code
        historique.append(code)

    return None, historique, "max_etapes"


# Application aux codes BDIFF non appariés

resultats_codes = []

for code in codes_non_apparies:

    code_actuel, historique, statut = trouver_code_actuel(code)

    resultats_codes.append(
        {
            "code_insee_bdiff": code,
            "code_insee_actuel": code_actuel,
            "statut": statut,
            "chaine_codes": " -> ".join(historique)
        }
    )


correspondance_codes = pd.DataFrame(resultats_codes)


# Ajout du nom de la commune actuelle

correspondance_codes = correspondance_codes.merge(
    communes[
        [
            "code_insee",
            "nom_standard"
        ]
    ],
    left_on="code_insee_actuel",
    right_on="code_insee",
    how="left"
)


# Suppression de la colonne technique issue de la jointure

correspondance_codes = correspondance_codes.drop(
    columns=["code_insee"],
    errors="ignore"
)


# Renommage pour plus de clarté

correspondance_codes = correspondance_codes.rename(
    columns={
        "nom_standard": "nom_commune_actuelle"
    }
)


# Résumé des résultats

print(
    "Nombre total de codes non appariés :",
    len(correspondance_codes)
)

print(
    "Codes rattachés à une commune actuelle :",
    (
        correspondance_codes["statut"] == "retrouve"
    ).sum()
)

print(
    "Cas complexes :",
    (
        correspondance_codes["statut"] == "cas_complexe"
    ).sum()
)

print(
    "Codes non retrouvés :",
    (
        correspondance_codes["statut"] == "non_retrouve"
    ).sum()
)


# Affichage des correspondances

display(
    correspondance_codes[
        [
            "code_insee_bdiff",
            "code_insee_actuel",
            "nom_commune_actuelle",
            "statut",
            "chaine_codes"
        ]
    ]
    .sort_values(
        [
            "statut",
            "code_insee_bdiff"
        ]
    )
)


# Vérification spécifique des cas non rattachés

display(
    correspondance_codes[
        correspondance_codes["statut"] != "retrouve"
    ][
        [
            "code_insee_bdiff",
            "statut",
            "chaine_codes"
        ]
    ]
)

Nombre d'anciens codes ayant plusieurs destinations : 3095
Nombre total de codes non appariés : 205
Codes rattachés à une commune actuelle : 11
Cas complexes : 191
Codes non retrouvés : 3

,code_insee_bdiff,code_insee_actuel,nom_commune_actuelle,statut,chaine_codes
90,01097,None,NaN,cas_complexe,01097
140,01316,None,NaN,cas_complexe,01316
144,04100,None,NaN,cas_complexe,04100
56,04198,None,NaN,cas_complexe,04198
54,05002,None,NaN,cas_complexe,05002
...,...,...,...,...,...
109,33092,33008,Porte-de-Benauge,retrouve,33092 -> 33008
80,33338,33055,Blaignan-Prignac,retrouve,33338 -> 33055
179,38312,38407,La Sure en Chartreuse,retrouve,38312 -> 38407
32,48033,48017,Banassac-Canilhac,retrouve,48033 -> 48017
106,63127,63335,Saint-Diéry,retrouve,63127 -> 63335

    code_insee_bdiff        statut chaine_codes
0              11298  cas_complexe        11298
2              11050  cas_complexe        11050
3              11097  cas_complexe        11097
4              30157  cas_complexe        30157
5              07016  cas_complexe        07016
..               ...           ...          ...
200            46326  cas_complexe        46326
201            05067  cas_complexe        05067
202            48197  cas_complexe        48197
203            48120  cas_complexe        48120
204            71492  cas_complexe        71492

[194 rows x 3 columns]

In [68]:
code_test = "11298"

display(
    mouvements[
        (mouvements["COM_AV"] == code_test) |
        (mouvements["COM_AP"] == code_test)
    ][
        [
            "MOD",
            "DATE_EFF",
            "COM_AV",
            "LIBELLE_AV",
            "COM_AP",
            "LIBELLE_AP"
        ]
    ]
    .sort_values("DATE_EFF")
)

    MOD    DATE_EFF COM_AV        LIBELLE_AV COM_AP        LIBELLE_AP
971  32  2019-01-01  11298  Pradelles-en-Val  11251      Val-de-Dagne
972  32  2019-01-01  11298  Pradelles-en-Val  11298  Pradelles-en-Val

In [69]:
resume_evenements = (
    mouvements[
        mouvements["COM_AV"].isin(codes_non_apparies)
    ]
    .groupby("COM_AV")
    .agg(
        nb_evenements=("COM_AV", "size"),
        nb_destinations=("COM_AP", "nunique"),
        premiere_date=("DATE_EFF", "min"),
        derniere_date=("DATE_EFF", "max")
    )
    .sort_values("nb_evenements", ascending=False)
)

display(resume_evenements.head(30))

        nb_evenements  nb_destinations premiere_date derniere_date
COM_AV
49101               6                2    2013-01-01    2016-01-01
16294               4                2    2013-11-08    2020-11-05
24439               4                2    2016-01-01    2017-01-01
24430               4                2    2016-01-01    2019-01-01
41169               4                2    2016-01-01    2017-01-01
49154               4                3    2016-01-01    2018-01-01
24435               4                2    2016-01-01    2017-01-01
24013               4                2    2016-01-01    2017-01-01
05034               3                2    1944-05-01    2016-01-01
05042               3                2    2013-01-01    2014-04-17
15068               3                2    2016-01-01    2021-01-01
12285               3                2    1954-09-11    2016-01-01
16004               3                2    2017-01-01    2020-11-05
16309               3                2    2018-01-01    2020-01-01
15171               3                2    2016-12-01    2025-01-01
05143               3                2    2016-01-01    2020-07-01
05088               3                2    2017-07-01    2017-07-01
05138               3                2    2013-01-01    2014-04-17
05175               3                2    2017-01-01    2020-09-30
16202               3                2    2019-01-01    2019-01-01
15035               3                2    2016-12-01    2025-01-01
56016               3                2    2019-01-01    2021-01-01
49157               3                2    2010-07-11    2016-01-01
48186               3                2    2016-01-01    2020-01-01
48022               3                2    2016-01-01    2020-01-01
48047               3                2    1972-06-02    2017-01-01
33091               3                2    2017-01-01    2020-01-01
27172               3                2    2016-01-01    2020-12-31
39036               3                2    2018-01-01    2020-01-01
35129               3                2    2016-01-01    2020-03-01

In [70]:
# CONSTRUCTION D'UNE CHAINE HISTORIQUE VERS UN CODE ACTUEL

# Préparation des dates

mouvements["DATE_EFF"] = pd.to_datetime(
    mouvements["DATE_EFF"],
    errors="coerce"
)

# On garde uniquement les lignes où le code change réellement

transitions = mouvements[
    mouvements["COM_AV"] != mouvements["COM_AP"]
].copy()

transitions = transitions.sort_values(
    ["COM_AV", "DATE_EFF"]
)


# Fonction de recherche du code actuel

def trouver_code_actuel_chrono(code, max_etapes=20):

    code_courant = str(code).strip()
    historique = [code_courant]

    for _ in range(max_etapes):

        # Si le code existe aujourd'hui
        if code_courant in codes_actuels:
            return code_courant, historique, "retrouve"

        # Toutes les transitions connues pour ce code
        candidats = transitions[
            transitions["COM_AV"] == code_courant
        ].copy()

        # Aucun événement trouvé
        if candidats.empty:
            return None, historique, "non_retrouve"

        # On prend la transition la plus récente
        candidats = candidats.sort_values(
            "DATE_EFF",
            ascending=False
        )

        nouveau_code = candidats.iloc[0]["COM_AP"]

        # Protection contre les boucles
        if nouveau_code in historique:
            return None, historique, "boucle"

        code_courant = nouveau_code
        historique.append(code_courant)

    return None, historique, "max_etapes"


# Application aux codes non appariés

resultats_codes = []

for code in codes_non_apparies:

    code_actuel, historique, statut = trouver_code_actuel_chrono(code)

    resultats_codes.append({
        "code_insee_bdiff": code,
        "code_insee_actuel": code_actuel,
        "statut": statut,
        "chaine_codes": " -> ".join(historique)
    })


correspondance_codes = pd.DataFrame(resultats_codes)


# Ajout du nom actuel

correspondance_codes = correspondance_codes.merge(
    communes[
        ["code_insee", "nom_standard"]
    ],
    left_on="code_insee_actuel",
    right_on="code_insee",
    how="left"
)

correspondance_codes = correspondance_codes.rename(
    columns={
        "nom_standard": "nom_commune_actuelle"
    }
)

correspondance_codes = correspondance_codes.drop(
    columns=["code_insee"],
    errors="ignore"
)


# Résumé

print(
    "Nombre total de codes non appariés :",
    len(correspondance_codes)
)

print(
    "Codes rattachés à une commune actuelle :",
    (correspondance_codes["statut"] == "retrouve").sum()
)

print(
    "Codes non retrouvés :",
    (correspondance_codes["statut"] == "non_retrouve").sum()
)

print(
    "Boucles détectées :",
    (correspondance_codes["statut"] == "boucle").sum()
)


# Affichage

display(
    correspondance_codes[
        [
            "code_insee_bdiff",
            "code_insee_actuel",
            "nom_commune_actuelle",
            "statut",
            "chaine_codes"
        ]
    ]
)

Nombre total de codes non appariés : 205
Codes rattachés à une commune actuelle : 202
Codes non retrouvés : 3
Boucles détectées : 0

,code_insee_bdiff,code_insee_actuel,nom_commune_actuelle,statut,chaine_codes
0,11298,11251,Val-de-Dagne,retrouve,11298 -> 11251
1,07252,07103,Saint-Julien-d'Intres,retrouve,07252 -> 07103
2,11050,11304,Quillan,retrouve,11050 -> 11304
3,11097,11323,Roquetaillade-et-Conilhac,retrouve,11097 -> 11323
4,30157,30052,Bréau-Mars,retrouve,30157 -> 30052
...,...,...,...,...,...
200,46326,46201,Montcuq-en-Quercy-Blanc,retrouve,46326 -> 46201
201,05067,05132,Saint-Bonnet-en-Champsaur,retrouve,05067 -> 05132
202,48197,48127,Monts-de-Randon,retrouve,48197 -> 48127
203,48120,48087,Prinsuéjols-Malbouzon,retrouve,48120 -> 48087
204,71492,71042,Bonnay-Saint-Ythaire,retrouve,71492 -> 71042

In [71]:
# VERIFICATION FINALE DES CORRESPONDANCES

print(correspondance_codes["statut"].value_counts())

display(
    correspondance_codes[
        correspondance_codes["statut"] != "retrouve"
    ]
)

statut
retrouve        202
non_retrouve      3
Name: count, dtype: int64

,code_insee_bdiff,code_insee_actuel,statut,chaine_codes,nom_commune_actuelle
22,83999,None,non_retrouve,83999,NaN
25,66999,None,non_retrouve,66999,NaN
41,06999,None,non_retrouve,06999,NaN

le niveau de feu par commune ou bien